### ISSUE TITLE
npm install fails with babel error

### ISSUE THREAD

**Issue by gfloyd** [slurmulon/hazy#3]
I'm getting the following error when locally installing hazy:

```
> hazy@0.1.8 build /var/www/my-project/node_modules/.staging/hazy-fa1f4369654be2f566535a0443dad8bf
> node ./node_modules/.bin/babel src --out-dir lib

ReferenceError: [BABEL] src/hazy.js: Unknown option: /var/www/my-project/.babelrc.presets
    at Logger.error (/var/www/my-project/node_modules/.staging/hazy-fa1f4369654be2f566535a0443dad8bf/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/var/www/my-project/node_modules/.staging/hazy-fa1f4369654be2f566535a0443dad8bf/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.addConfig (/var/www/my-project/node_modules/.staging/hazy-fa1f4369654be2f566535a0443dad8bf/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/var/www/my-project/node_modules/.staging/hazy-fa1f4369654be2f566535a0443dad8bf/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/var/www/my-project/node_modules/.staging/hazy-fa1f4369654be2f566535a0443dad8bf/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/var/www/my-project/node_modules/.staging/hazy-fa1f4369654be2f566535a0443dad8bf/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/var/www/my-project/node_modules/.staging/hazy-fa1f4369654be2f566535a0443dad8bf/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/var/www/my-project/node_modules/.staging/hazy-fa1f4369654be2f566535a0443dad8bf/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Object.exports.transform (/var/www/my-project/node_modules/.staging/hazy-fa1f4369654be2f566535a0443dad8bf/node_modules/babel/lib/babel/util.js:40:22)
    at Object.exports.compile (/var/www/my-project/node_modules/.staging/hazy-fa1f4369654be2f566535a0443dad8bf/node_modules/babel/lib/babel/util.js:49:20)
```

It looks like it's because I'm using a newer version of Babel that has an option in my .babelrc that isn't supported by Babel 5. Do you think it would make sense to publish the lib dir and remove the `preinstall` script? It looks like you already have the build as part of `prepublish`, but the lib dir isn't in the npm package since it's in .gitignore.

Happy to submit a PR if you want!

**Comment by slurmulon** [comment]
@gfloyd apoligies for the horrendous response time on this, I don't have a very good reason other than being way too busy and having lots of unread notifications.  I will do my best to improve on that front.

>  Do you think it would make sense to publish the lib dir and remove the preinstall script?

The only reason I didn't do this to begin with is because I don't like checking in compiled library code that parallels my source code changes, it's simply a personal preference I've developed over time. If it makes people's live's easier to publish `lib` then I'm more than happy to support it.

> It looks like it's because I'm using a newer version of Babel that has an option in my .babelrc that isn't supported by Babel 5.

As of `0.1.13`, Babel 6 is now used along with some syntax plugins (`es2015`, `syntax-flow`, `transform-flow-strip-types`)

> Do you think it would make sense to publish the lib dir and remove the preinstall script?

There are a couple reasons I'm using the  `preinstall` script. 

1. This is a remnant from a hacky `package.json` built around Babel 5. Babel 5 had various packaging issues but the most prominent was that it failed to install (as other packages do) before `postinstall`. After a lot of searching I ended up  running `npm install --ignore-scripts` in `preinstall` - pretty gross.  

2. I have found, that for a reason I'm not sure of yet, that Babel 6 fails to install completely as well unless you provide `npm install --ignore-scripts` in `preinstall`. If you have suggestions on avoiding this problem (preferably without needing to publish `lib`) then I'm all ears!

> Happy to submit a PR if you want!

Please and thank you! Hoping these issues weren't too frustrating for you, and again apologies for the extremely slow response.

**Comment by slurmulon** [comment]
As of `0.1.16`, hazy no longer requires the host to compile/transclude the library on their own machine. This was mostly due to me doing whatever I could to avoid publishing output folders. After realizing that NPM actually processes your .gitignore file, I addressed the issue by creating an `.npmignore` that doesn't include `lib`.

There is no need to build on the host, therefore this exception should no longer be possible. It's definitely no longer an issue after the Babel 6 upgrade in `0.1.13`
